### PR TITLE
jenkins build failed and local don't build for me.

### PR DESCRIPTION
**Pull request by maxandersen**
Can someone verify/tell me what is supposedely wrong with this new entry ?

### CODE REVIEW

**Comment by hferentschik** [comment]
Out of interest, why are you using erb files? The existing erb files are a result from the import of the old blog posts. It was easier for us to import HTML (aka erb files). However, new blog posts can be written in Markdown or Asciidoc. I think most of us prefer the latter. See also https://github.com/hibernate/in.relation.to#write-a-blog

**Comment by hferentschik** [comment]
> local don't build for me

Just for this post or in general? If the latter, have you tried the Docker based approach - https://github.com/hibernate/in.relation.to/tree/staging/docker

**Comment by hferentschik** [comment]
BTW, seems there are issues with the Jenkins setup. Hang tight ;-)

**Comment by dreab8** [comment]
the problem seems related with the file name

2016-01-12-jboss-community-asylum-hibernate-strikes-back-episode-v.erb

instead of

2016-01-12-jboss-community-asylum-hibernate-strikes-back-episode-v._html_
.erb

**Comment by maxandersen** [comment]
I use the .erb files because I haven't been able to get anything else to work/look remotely decent but mainly because it was faster :)

**Comment by hferentschik** [comment]
Merged. I was so free to change the date to make it appear as the latest blog and I added some 'br' at the end, since your image was higher than your text column which caused some problems with the horizontal divider.

**Pull request closed without merging**
