### PR TITLE
WEBSITE-279 Hero text box

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/WEBSITE-279

As text I used the one in the JIRA:
`The Hibernate team blog on everything data.`

### CODE REVIEW

**Comment by DavideD** [comment]
> i am confused, why do we need the releases and release_file_parser extensions back?

For the blog I use the same hero box that we use for the projects. This hero box also include some buttons that appear only if the project has a release. Without adding those dependencies some warning appear during the build of the website (because a function is not found). I prefer to add the dependencies than change the existing function for the hero box.

**Comment by gunnarmorling** [comment]
@DavideD I am getting the following error:

undefined method `[]' for nil:NilClass
Rendering file /Users/gunnar/Development/in.relation.to/index.html.haml resulted in a failure.

Line: unknown

Backtrace:

/.../in.relation.to/_layouts/project.html.haml:7:in `block in singleton class'
/.../in.relation.to/_layouts/project.html.haml:-9:in `instance_eval'
/.../in.relation.to/_layouts/project.html.haml:-9:in `singleton class'
/.../in.relation.to/_layouts/project.html.haml:-11:in `__tilt_70199118552040'

Any idea what could be wrong?

**Comment by gunnarmorling** [comment]
Hum, if I declare a "project" in site.yml it works. I don't think though we need the notion of project at all for the blog? I'd rather have a simple hero box (it's just a boostrap style really) and don't pull in the release parser etc. This all seems not needed AFAICS.

**Comment by hferentschik** [comment]
+1

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Mon, Jun 22, 2015 at 14:07, hibernate/in.relation.to
<reply@reply.github.com>
wrote:
Hum, if I declare a "project" in site.yml it works. I don't think though we need
the notion of project at all for the blog? I'd rather have a simple hero box
(it's just a boostrap style really) and don't pull in the release parser etc.
This all seems not needed AFAICS.

—
Reply to this email directly or view it on GitHub
[https://github.com/hibernate/in.relation.to/pull/29#issuecomment-114080642] .[https://github.com/notifications/beacon/AASFouI81c1NX1YFBFeG-A-nwqWUBsRhks5oV_H3gaJpZM4FHSZq.gif]

**Comment by DavideD** [comment]
I've changed it.
I added a partial hero box for the blog

**Pull request merged**
