### PR TITLE
WEBSITE-334 tag author list

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/WEBSITE-334

For the author posts I've addded the Bio above the authors list. It looks nice.

I also added the feed link to the pages as a separate commit.

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
Looks right.
But should we also do this on blog post pages like http://localhost:4242/2015/03/17/hibernate-ogm-times-2413-and-42-beta-1-released/ ?

**Comment by emmanuelbernard** [comment]
Going to apply in the mean time.

**Comment by emmanuelbernard** [comment]
but leave the issue opened.

**Comment by DavideD** [comment]
> But should we also do this on blog post pages like http://localhost:4242/2015/03/17/hibernate-ogm-times-2413-and-42-beta-1-released/ ?


I think so, there is already an issue related to this:  https://hibernate.atlassian.net/browse/WEBSITE-320

**Pull request closed without merging**
