### PR TITLE
Hibernate Reactive 1.0.0.CR4 release post

### PR DESCRIPTION
**Pull request by DavideD**
Also available on staging: https://staging.in.relation.to/2021/04/30/hibernate-reactive-1_0_0_CR4/

### CODE REVIEW

**Comment by gavinking** [comment]
Great!

**Comment by DavideD** [comment]
Fixed the syntax

**Comment by DavideD** [comment]
@gavinking is the post good enough?

**Comment by gavinking** [comment]
I would say:

> It’s now possible to use Hibernate Reactive with **both** Hibernate ORM 5.4 and Hibernate ORM 5.5.

Or explicitly clarify that we previously only supported 5.4.

Also I would clarify that no code changes are needed for people using `withSession()` as recommended.

**Comment by DavideD** [comment]
Ah, good point. I'm going to eat something and then I will update it

**Comment by DavideD** [comment]
Merged!
Thanks

**Pull request merged**
