### PR TITLE
Small post about Duration validation

### PR DESCRIPTION
**Pull request by marko-bekhta**
Good time of day to you @gunnarmorling  and @gsmet :)

I know that the previous post is still pending (I cleaned the other one a bit and moved the examples around as you've asked), but I was thinking that this one can be useful and interesting. As we can show others how we decided to validate `Duration` and get some feedback from users, so we will know what do they think of it.

I've tried to be as brief as possible on this one :)

Also it should probably go after the first one as it is missing "author" part and will fail to build correctly without it.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks, @marko-bekhta. Question is whether you want to mention `@DurationMax/Min` in the HV 6 Alpha1 release announcement, @gsmet? Do we then still need a separate follow-up post? Personally I think it'd be better handled (just showing the usage) in the release announcement. WDYT?

**Comment by gsmet** [comment]
It's indeed part of the release announcement.

**Comment by marko-bekhta** [comment]
@gunnarmorling @gsmet well yes, if there's a place for it in HV6 release announcement than definitely  better put it there. If you don't have it ready yet, and example in here is good enough - you can use it :)

**Comment by gsmet** [comment]
Closing, it was integrated in the HV6 release announcement.

**Pull request closed without merging**
