### PR TITLE
first try on add blog post

### PR DESCRIPTION
**Pull request by maxandersen**

### CODE REVIEW

**Comment by hferentschik** [comment]
@maxandersen, if you are happy with the posts and it works, just go ahead and push. What I mean is, you can push this to staging and check the result after the ci built completed under staging.in.relation.to. If all is good push the changes to production. See also http://in.relation.to/README/#preview-changes-on-staging-in-relation-to

**Comment by hferentschik** [comment]
@maxandersen for your convenience - http://staging.in.relation.to/ :-)
btw, you should sync with the production branch when adding a blog post. Staging is often behind.

**Comment by hferentschik** [comment]
Rebased and merged to production

**Comment by maxandersen** [comment]
ah sorry, I forgot to add in description that this publish dont' seem to work ;/
the page dont show up when I run locally hence why I didn't want to push to staging directly.

**Comment by maxandersen** [comment]
but apparently it does when pushing it to the servers...great ;)

**Comment by hferentschik** [comment]
> the page dont show up when I run locally hence why I didn't want to push to staging directly.

I see. Any exceptions? Your awestruct environment otherwise running? Sounds odd that your post would not appear provided you were able to view the site otherwise.

> but apparently it does when pushing it to the servers...great ;)

jupp, no problems at all

**Pull request closed without merging**
