### PR TITLE
#294 More clearly structuring between posts in list views; Unifying d…

### PR DESCRIPTION
**Pull request by gunnarmorling**
…isplay of posts

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
I don't think I like it very much to move the tags so far away.
Why do we need a permalink link for? We already have the title.

Wasn't a more prominent hr (fatter and with more space) solve the issue, esp if we combine it with the h1/h2 discussion

**Comment by gunnarmorling** [comment]
> I don't think I like it very much to move the tags so far away.

Last week you still doubted anyone would read the tags at all ;)

How about the following, using more space and the author image next to the title. Gives a more personal touch and makes it very apparent where posts start/end.

screen shot 2015-06-22 at 15 04 00

**Comment by hferentschik** [comment]
+1 sounds like a nice idea

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Mon, Jun 22, 2015 at 15:08, hibernate/in.relation.to
<reply@reply.github.com>
wrote:
I don't think I like it very much to move the tags so far away.

Last week you still doubted anyone would read the tags at all ;)

How about the following, using more space and the author image next to the
title. Gives a more personal touch and makes it very apparent where posts
start/end.

screen shot 2015-06-22 at 15 04 00
[https://cloud.githubusercontent.com/assets/28612/8282368/6b0d7798-18f0-11e5-8ae9-7a5490cb0836.png]
[https://cloud.githubusercontent.com/assets/28612/8282368/6b0d7798-18f0-11e5-8ae9-7a5490cb0836.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/hibernate/in.relation.to/pull/32#issuecomment-114096503] .[https://github.com/notifications/beacon/AASFoj8tnXHL0P_KUF7NZtbK_hpd6Kteks5oWABbgaJpZM4FI3Mn.gif]

**Comment by emmanuelbernard** [comment]
Very good idea @gunnarmorling. fire away.

**Comment by gunnarmorling** [comment]
Pushed one more commit for adding the author images and moving the tags back up.

**Comment by emmanuelbernard** [comment]
This change does not work too well on phone size. Should you hide the pic in this case?

**Comment by gunnarmorling** [comment]
Ok, rebased and force-pushed another update:

* Scaling is better now; Image and title stay on one line; On phones the author image isn't shown
* On the author pages no author image is shown next to titles
* The Hibernate logo is used for people without a gravatar

**Comment by hferentschik** [comment]
Merged. Thank @gunnarmorling, that was a good one

**Comment by gunnarmorling** [comment]
Cool; Glad to hear you like it :)

**Pull request closed without merging**
