### PR TITLE
Match the navigation menu from hibernate.org

### PR DESCRIPTION
**Pull request by marko-bekhta**

### CODE REVIEW

**Review by gavinking — APPROVED** [review]
Ah, yes, thanks!

**Comment by gsmet** [comment]
@marko-bekhta probably not high priority but you might be interested in what we're doing with Surge.sh to provide a preview for quarkus.io.

Interesting parts would be:

- https://github.com/quarkusio/quarkusio.github.io/blob/80316acb7f59a866db0179a9893538355338a2dc/.github/workflows/build.yml#L80-L85 (where we build an artifact with the website)
- https://github.com/quarkusio/quarkusio.github.io/blob/main/.github/workflows/preview.yml
- https://github.com/quarkusio/quarkusio.github.io/blob/main/.github/workflows/preview-teardown.yml

We chain the workflows for security reason as you need a token to publish to surge.

Let me know if you decide to move on this, I'll be happy to help if you encounter any issue.

**Comment by gavinking** [comment]
@marko-bekhta I have tested this in staging and it looks good. Shall we just merge it?

**Review by gavinking — APPROVED** [review]

**Comment by gavinking** [comment]
Check out https://staging.in.relation.to :)

**Comment by marko-bekhta** [comment]
@gsmet thanks! That's a nice idea. I've created a task in our backlog so we don't forget about it 😃

**Comment by marko-bekhta** [comment]
> @marko-bekhta I have tested this in staging and it looks good. Shall we just merge it?

ok 🙈 let's do it 😃

**Pull request merged**
