### PR TITLE
WEBSITE-289 Add disqus comments counter

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/WEBSITE-289

I've already applied the changes in staging, if you guys want to have a look

### CODE REVIEW

**Comment by DavideD** [comment]
It seems there are some problems with some posts without comments: http://staging.in.relation.to/2013/09/12/hibernate-orm-430-beta-4-release/

@hferentschik  Any idea what might be wrong? Do you see something wrong in the disqus id (12-09-2013-hibernate-orm-430-beta-4-release)?

**Comment by hferentschik** [comment]
Took me a while to realize what you are talking about :-) Just to make sure, we are talking about the blog "summary" under the title. You basically adding a comment count link
with-count
without-count
If there is at least one comment all is good, but for posts with zero comments, nothing is rendered.

> Any idea what might be wrong? Do you see something wrong in the disqus id (12-09-2013-hibernate-orm-430-beta-4-release)?

Nope, when looking at the post it properly displays '0 comments' at the bottom, so the integration seems to work.

Otherwise a nice little gimmick.

**Comment by hferentschik** [comment]
Actually the problem does not seem to be related to zero comments in general. Here for example we have multiple zero comments - http://staging.in.relation.to/emmanuel-bernard/ - and it works ok. Also, I created a test comment, but the display of comments still did not work :-(

**Comment by hferentschik** [comment]
Maybe you can check with Firebug which request the underlying JavaScript tries to make. Maybe you see an error there or if not you can then try curl to do the same request. Maybe this  will show you where the problem is.

**Comment by hferentschik** [comment]
Closing this pull request. Seems we need to get back to the drawing board first on this one.

**Pull request closed without merging**
